version: "3"

services:

    web_pay:
        build: ./web
        restart: always
        environment:
            - APACHE_RUN_USER=#1000
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        ports:
            - 10060:80
        working_dir: ${APP_PATH_CONTAINER}

    db_pay:
        build: ./db
        command: "--innodb_use_native_aio=0 --default-authentication-plugin=mysql_native_password"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: pay.api_db
        volumes:
            - ${DB_PATH_HOST}:/var/lib/mysql

    phpmyadmin_pay:
        build: ./phpmyadmin
        links:
            - db_pay
        restart: always
        ports:
            - 10061:80
        environment:
            - PMA_HOST=db_pay
            - PMA_PORT=3306
            - PMA_ARBITRARY=1

    composer_pay:
        image: composer
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        working_dir: ${APP_PATH_CONTAINER}
        command: composer install
